services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
